### ISSUE TITLE
Error 500 on create work_log

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#44]
Did a POST on /users/180/work_logs to create a new work log entry. Received error 500. Log is captured below.

Body: `{id: "-1", date: "2019-02-09", siteid: "1", hours: "5", approved: "false"}`

`D, [2018-12-05T14:45:23.092111 #21453] DEBUG -- : [10fa20c2-ccb4-451a-8eac-3306d0b85dda] Logging work for user: 180
D, [2018-12-05T14:45:23.092211 #21453] DEBUG -- : [10fa20c2-ccb4-451a-8eac-3306d0b85dda] Params: {"id"=>"-1", "date"=>"2019-02-08", "siteid"=>"1", "hours"=>"5", "approved"=>"false", "controller"=>"work_logs", "action"=>"create", "user_id"=>"180", "work_log"=>{"hours"=>"5", "date"=>"2019-02-08", "approved"=>"false"}}
D, [2018-12-05T14:45:23.092417 #21453] DEBUG -- : [10fa20c2-ccb4-451a-8eac-3306d0b85dda] Logging work with settings: {"hours"=>"5", "date"=>"2019-02-08", "approved"=>"false"}
D, [2018-12-05T14:45:23.092497 #21453] DEBUG -- : [10fa20c2-ccb4-451a-8eac-3306d0b85dda] Params: {"id"=>"-1", "date"=>"2019-02-08", "siteid"=>"1", "hours"=>"5", "approved"=>"false", "controller"=>"work_logs", "action"=>"create", "user_id"=>"180", "work_log"=><ActionController::Parameters {"hours"=>"5", "date"=>"2019-02-08", "approved"=>"false"} permitted: false>}
D, [2018-12-05T14:45:23.093062 #21453] DEBUG -- : [10fa20c2-ccb4-451a-8eac-3306d0b85dda]    (0.1ms)  BEGIN
D, [2018-12-05T14:45:23.093986 #21453] DEBUG -- : [10fa20c2-ccb4-451a-8eac-3306d0b85dda]    (0.1ms)  ROLLBACK
I, [2018-12-05T14:45:23.102582 #21453]  INFO -- : [10fa20c2-ccb4-451a-8eac-3306d0b85dda] {"method":"POST","path":"/users/180/work_logs","format":"json","controller":"WorkLogsController","action":"create","status":500,"error":"NameError: undefined local variable or method `log' for #\u003cWorkLogsController:0x007f2c463524a0\u003e\nDid you mean?  loop","duration":12.0,"view":0.0,"db":0.52,"time":"2018-12-05T14:45:23.090+00:00","params":{"id":"-1","date":"2019-02-08","siteid":"1","hours":"5","approved":"false","controller":"work_logs","action":"create","user_id":"180","work_log":{"hours":"5","date":"2019-02-08","approved":"false"}},"cookie":"_rails-base_session=SnE4Unc5T1ZoT0Jia0FTQVZVWHBrR3BudCttcnNhQnBFcGJiTEE5SVQwRlc4Vk05cWtBTHY5WFhJLzVuNUtaUXl0eDlySDc2N1c4R1R2NWR2aldtbS9wcW1zWlBsYXVhTXdKQ1paSGJsZDBZV0J6SHhDY2grcHpsM0F4SlVZelVMSVlxTXNRdWQwblBIbmdNWTBRa1kvYXpERUFMaGFOMXZFK3h1TndET00wPS0tYUlvcG5mRnJDRlkvTDMxMVdCaUJ2UT09--db93aa59b457963c3bc7ee30e66b8c06a3536b33","@timestamp":"2018-12-05T14:45:23.102Z","@version":"1","message":"[500] POST /users/180/work_logs (WorkLogsController#create)"}
F, [2018-12-05T14:45:23.103064 #21453] FATAL -- : [10fa20c2-ccb4-451a-8eac-3306d0b85dda]   
F, [2018-12-05T14:45:23.104946 #21453] FATAL -- : [10fa20c2-ccb4-451a-8eac-3306d0b85dda] NameError (undefined local variable or method `log' for #<WorkLogsController:0x007f2c463524a0>
Did you mean?  loop):
F, [2018-12-05T14:45:23.105003 #21453] FATAL -- : [10fa20c2-ccb4-451a-8eac-3306d0b85dda]   
F, [2018-12-05T14:45:23.105035 #21453] FATAL -- : [10fa20c2-ccb4-451a-8eac-3306d0b85dda] app/controllers/work_logs_controller.rb:20:in `block (2 levels) in create'
[10fa20c2-ccb4-451a-8eac-3306d0b85dda] app/controllers/work_logs_controller.rb:18:in `create'`

**Comment by coxthepilot** [comment]
is fixed
